# Exemples algebra # 

In [1]:
import numpy as np

 Exemples de vectors (array)

In [2]:
v=np.array([1,0,0])
u=np.array([0,-2,0])

In [4]:
print(u)

[ 0 -2  0]


Operacións amb vectors (suma, resta, producte escalar/vectorial)

In [6]:
w1=u+v
print (w1)
w2=u-v
print(w2)

[ 1 -2  0]
[-1 -2  0]


In [8]:
a=np.dot (u,v)
print (a)

0


In [9]:
b=np.cross(u,v)
print(b)

[0 0 2]


In [10]:
b2=np.cross(v,u)
print(b2)

[ 0  0 -2]


Exemples amb matrius

In [13]:
A=np.array([[2,4,],[1,3]])
print(A)

[[2 4]
 [1 3]]


e=A[0,1]        #element 0 (fila) de la columna 1 (els calcula començen en 0)
print (e)

In [27]:

v=A[0,:]    #el primer 0 i el segon tots els num (dona tota la fila)
print(v)

[2 2]


In [19]:
u=A[:,1]
print (u)

[4 3]


Valors i vectors propis

In [21]:
A=np.array([[2,2],[1,3]])

In [25]:
Valors, vectors=np.linalg.eig(A)
print("valors propis",Valors)
print("vectors propis", vectors)

valors propis [1. 4.]
vectors propis [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [26]:
u=vectors[:,0]
print (u)

[-0.89442719  0.4472136 ]


In [30]:
v=vectors[:,1]
print(v)

[-0.70710678 -0.70710678]


Comprovem que son vectors propis

In [31]:
z=np.dot(A,v)
print (z)

[-2.82842712 -2.82842712]


In [32]:
z2=np.dot(A,u)
print(z2)

[-0.89442719  0.4472136 ]


Altres exemples de matrius

In [36]:
A=np.zeros([3,3])
print (A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
